import type { OperationDefinition } from '@creator-studio/contracts'
import type { ProviderCapability } from '../providers/generation-provider.js'

/**
 * MVP Operation 矩阵（04-runtime §2.3）。
 * 定义全部注册到 Registry；executor 未实现的返回 `OPERATION_NOT_IMPLEMENTED`。
 */
export const operationDefinitions: OperationDefinition[] = [
  // ── Topic → Outline / Script（create）──
  {
    id: 'generate_outline',
    label: '生成大纲',
    description: '根据选题生成内容大纲',
    behavior: 'create',
    input: { roles: ['inspiration', 'topic'] },
    output: { kind: 'text', role: 'outline', behavior: 'new_artifact' },
    defaultConfig: { length: 'medium' },
    executor: 'operation.generate_outline',
    presentation: { group: 'generate', priority: 10, placement: 'primary', danger: false },
    runtime: { streaming: true, cancellable: true, retryable: true, expectedDuration: 'medium' },
  },
  {
    id: 'generate_script',
    label: '生成口播稿',
    description: '根据大纲生成口播脚本',
    behavior: 'create',
    input: { roles: ['outline'] },
    output: { kind: 'text', role: 'script', behavior: 'new_artifact' },
    defaultConfig: { tone: 'natural' },
    executor: 'operation.generate_script',
    presentation: { group: 'generate', priority: 10, placement: 'primary', danger: false },
    runtime: { streaming: true, cancellable: true, retryable: true, expectedDuration: 'long' },
  },
  // ── Transform（new_version）──
  {
    id: 'polish',
    label: '润色',
    description: '润色文本，提升表达',
    behavior: 'transform',
    input: { kinds: ['text'], roles: ['topic', 'outline', 'script'] },
    output: { behavior: 'new_version' },
    defaultConfig: {},
    executor: 'operation.polish',
    presentation: { group: 'edit', priority: 20, placement: 'secondary', danger: false },
    runtime: { streaming: true, cancellable: true, retryable: true, expectedDuration: 'short' },
  },
  {
    id: 'edit',
    label: '编辑',
    description: '手动编辑当前内容（revisioned patch）',
    behavior: 'transform',
    input: { kinds: ['text', 'image', 'audio', 'video', 'collection'] },
    output: { behavior: 'new_version' },
    defaultConfig: {},
    executor: 'operation.edit',
    presentation: { group: 'edit', priority: 0, placement: 'primary', danger: false },
    runtime: { expectedDuration: 'instant' },
  },
  // ── Branch（并行新 Artifact）──
  {
    id: 'branch',
    label: '创建分支',
    description: '基于当前版本创建并行分支',
    behavior: 'branch',
    input: { kinds: ['text', 'image', 'audio', 'video', 'collection'] },
    output: { kind: 'text', role: 'topic', behavior: 'new_artifact' },
    defaultConfig: {},
    executor: 'operation.branch',
    presentation: { group: 'edit', priority: 90, placement: 'secondary', danger: false },
    runtime: { expectedDuration: 'instant' },
  },
  // ── Media（Issue #10 接真实 provider，此处 executor 占位）──
  {
    id: 'generate_cover',
    label: '生成封面',
    description: '根据当前内容生成封面候选',
    behavior: 'create',
    input: { roles: ['inspiration', 'topic', 'outline', 'script'] },
    output: { kind: 'image', role: 'cover', behavior: 'new_collection' },
    defaultConfig: { count: 3 },
    executor: 'operation.generate_cover',
    presentation: { group: 'media', priority: 10, placement: 'secondary', danger: false },
    runtime: { cancellable: true, retryable: true, expectedDuration: 'long' },
  },
  {
    id: 'generate_image',
    label: '生成图片',
    description: '根据提示词和可选参考图生成候选集',
    behavior: 'create',
    input: {},
    output: { kind: 'image', role: 'illustration', behavior: 'new_collection' },
    defaultConfig: { count: 4, size: '1024x1024', quality: 'medium' },
    executor: 'operation.image_candidates',
    presentation: { group: 'media', priority: 5, placement: 'primary', danger: false },
    runtime: { cancellable: true, retryable: true, expectedDuration: 'long' },
  },
  ...(['edit_image', 'outpaint_image', 'vary_image', 'enhance_image'] as const).map((id, index): OperationDefinition => ({
    id,
    label: id === 'edit_image' ? '编辑图片' : id === 'outpaint_image' ? '扩展画面' : id === 'vary_image' ? '生成变体' : 'AI 增强',
    description: id === 'outpaint_image' ? '使用蒙版扩展图片边界' : '基于当前图片生成新的候选集',
    behavior: 'create',
    input: { kinds: ['image'] },
    output: { kind: 'image', role: id.replace('_image', ''), behavior: 'new_collection' },
    defaultConfig: { count: 4, size: '1024x1024', quality: 'medium' },
    executor: 'operation.image_candidates',
    presentation: { group: 'media', priority: 10 + index, placement: id === 'edit_image' ? 'primary' : 'secondary', danger: false },
    runtime: { cancellable: true, retryable: true, expectedDuration: 'long' },
  })),
  {
    id: 'generate_voice',
    label: '生成配音',
    description: '根据脚本生成配音（TTS）',
    behavior: 'create',
    input: { roles: ['inspiration', 'topic', 'outline', 'script'] },
    output: { kind: 'audio', role: 'voice', behavior: 'new_artifact' },
    defaultConfig: {},
    executor: 'operation.generate_voice',
    presentation: { group: 'media', priority: 20, placement: 'secondary', danger: false },
    runtime: { cancellable: true, retryable: true, expectedDuration: 'long' },
  },
  // ── Action（publish 骨架）──
  {
    id: 'publish',
    label: '发布',
    description: '发布内容到目标平台（MVP 骨架）',
    behavior: 'action',
    input: { roles: ['script', 'video'] },
    output: { behavior: 'side_effect' },
    defaultConfig: {},
    executor: 'operation.publish',
    presentation: { group: 'publish', priority: 100, placement: 'primary', danger: true },
    runtime: { cancellable: true, retryable: true, expectedDuration: 'medium' },
  },
  // ── 矩阵其余定义（executor 未实现 → NOT_IMPLEMENTED）──
  {
    id: 'research',
    label: '调研素材',
    behavior: 'transform',
    input: { roles: ['topic'] },
    output: { behavior: 'new_version' },
    defaultConfig: {},
    executor: 'operation.not_implemented',
    presentation: { group: 'generate', priority: 30, placement: 'secondary', danger: false },
    runtime: { expectedDuration: 'long' },
  },
  {
    id: 'rewrite',
    label: '改写',
    behavior: 'transform',
    input: { kinds: ['text'], roles: ['topic', 'outline', 'script'] },
    output: { behavior: 'new_version' },
    defaultConfig: {},
    executor: 'operation.rewrite',
    presentation: { group: 'edit', priority: 30, placement: 'secondary', danger: false },
    runtime: { expectedDuration: 'medium' },
  },
  {
    id: 'expand',
    label: '扩写',
    behavior: 'transform',
    input: { kinds: ['text'], roles: ['outline', 'script'] },
    output: { behavior: 'new_version' },
    defaultConfig: {},
    executor: 'operation.not_implemented',
    presentation: { group: 'edit', priority: 40, placement: 'secondary', danger: false },
    runtime: { expectedDuration: 'medium' },
  },
  {
    id: 'shorten',
    label: '精简',
    behavior: 'transform',
    input: { kinds: ['text'], roles: ['outline', 'script'] },
    output: { behavior: 'new_version' },
    defaultConfig: {},
    executor: 'operation.not_implemented',
    presentation: { group: 'edit', priority: 50, placement: 'secondary', danger: false },
    runtime: { expectedDuration: 'medium' },
  },
  {
    id: 'generate_article',
    label: '生成图文',
    behavior: 'create',
    input: { roles: ['outline'] },
    output: { kind: 'text', role: 'article', behavior: 'new_artifact' },
    defaultConfig: {},
    executor: 'operation.not_implemented',
    presentation: { group: 'generate', priority: 40, placement: 'secondary', danger: false },
    runtime: { expectedDuration: 'long' },
  },
  {
    id: 'generate_images',
    label: '生成配图',
    behavior: 'create',
    input: { roles: ['inspiration', 'topic', 'outline', 'script'] },
    output: { kind: 'image', role: 'illustration', behavior: 'new_collection' },
    defaultConfig: {},
    executor: 'operation.image_candidates',
    presentation: { group: 'media', priority: 30, placement: 'secondary', danger: false },
    runtime: { expectedDuration: 'long' },
  },
  {
    id: 'generate_video',
    label: '生成视频',
    behavior: 'create',
    input: { roles: ['inspiration', 'topic', 'outline', 'script', 'voice'] },
    output: { kind: 'video', role: 'draft', behavior: 'new_artifact' },
    defaultConfig: {},
    executor: 'operation.generate_video',
    presentation: { group: 'media', priority: 50, placement: 'secondary', danger: false },
    runtime: { expectedDuration: 'long' },
  },
]

/** 每个 Operation 需要的 Provider 能力（executor 选择 provider 用）。 */
export const operationCapability: Record<string, ProviderCapability> = {
  generate_outline: 'text_generation',
  generate_script: 'text_generation',
  polish: 'text_generation',
  research: 'text_generation',
  rewrite: 'text_generation',
  expand: 'text_generation',
  shorten: 'text_generation',
  generate_article: 'text_generation',
  generate_cover: 'image_generation',
  generate_images: 'image_generation',
  generate_image: 'image_generation',
  edit_image: 'image_generation',
  outpaint_image: 'image_generation',
  vary_image: 'image_generation',
  enhance_image: 'image_generation',
  generate_voice: 'audio_generation',
  generate_video: 'video_generation',
}
